singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: ${REDIS_PASSWORD}
  subscriptionsPerConnection: 5
  clientName: null
  address: ${REDIS_HOST}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
codec: !<org.redisson.codec.JsonJacksonCodec> { }
transportMode: NIO